### ISSUE TITLE
Rationale for TPM and RPKM

### ISSUE THREAD

**Issue by ChelseaCHENX** [DavisLaboratory/standR#21]
Hi there! Really appreciate your work in standR - it is comprehensive and helps a lot!

Meanwhile, I have one question regarding the rationale of calculating TPM and RPKM (ie, gene length normalization) - in tutorial, it suggests adding gene length to object for edgeR-based calculation. However, geomx is a probe based method, and eg, in WTA, each gene has one probe of uniform length (`Hs_R_NGS_WTA_v1.0.pkc`), thus I think normalization without gene length (eg, TMM) is sufficient. This thought is generated while doing deconvolution - eg, xcell requires gene length normalization, while in this logic, we do not need to use RPKM / TPM (but TMM / CPM) for xcell in GeoMx WTA data.

Would love to hear your comments as well and thanks a lot!

**Comment by ningbioinfo** [comment]
Hi @ChelseaCHENX, you're correct, I would always recommend user to use normalisation strategies without gene length when doing DE analysis. TPM and RPKM was first added as options is due to some databases of RNA-seq only provide RPKM count, having RPKM/TPM as options would make the function more flexible. I'll add add reminders in the documentation of the normalization function to give user notices about it.
